server {
    listen 80;
    charset utf-8;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Type "text/html; charset=utf-8";

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
